
env:
   global:
     - CONAN_REFERENCE: "webots-controller/R2020a-rev1"
     - CONAN_USERNAME: "anotherfoxguy"
     - CONAN_LOGIN_USERNAME: "anotherfoxguy"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/anotherfoxguy/conan-packages"

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
    env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
